name: 🚀 IPTV Auto Pipeline

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Import external sources
        run: python Code/run: python Code/import_external_m3u_sources.py

      -  name: Import IPTV-org
        run: python Code/import_iptv_org_vod.py

      -  name: Run pipeline
        run: python Code/pipeline_iptv.py

      -  name: Commit update
         run: |
          git config user.name "iptv-bot"
          git config user.email "iptv-bot@users.noreply.github.com"

           git add .

            if git diff --cached --quiet; then
            echo "No changes"
            else
            git commit -m "auto update"
            git push
            fi
