name: 🚀 IPTV Auto Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Import anime sources
        run: python Code/import_external_m3u_sources.py

      - name: Import IPTV-org VOD
        run: python Code/import_iptv_org_vod.py

      - name: Import scalable VOD playlists
        run: python Code/import_vod_playlists.py

      - name: Run pipeline
        run: python Code/pipeline_iptv.py

      - name: Enrich anime metadata
        run: python Code/enrich_anime_metadata.py

      - name: Commit update
        run: |
          git config user.name "iptv-bot"
          git config user.email "iptv-bot@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "auto update VOD scale"
            git push
          fi
